Repository Leets-Official/SEEAT-BE, pull requests merged in 2025-07, with the labels that each got.

#3 🔨 chore: DB 스키마 구성 및 설계 PR
  src/main/java/com/seeat/server/ServerApplication.java
  src/main/java/com/seeat/server/domain/BaseEntity.java
  src/main/java/com/seeat/server/domain/manage/application/FeedbackService.java
  src/main/java/com/seeat/server/domain/manage/application/FeedbackUseCase.java
  src/main/java/com/seeat/server/domain/manage/domain/entity/Feedback.java
  src/main/java/com/seeat/server/domain/manage/domain/repository/FeedbackRepository.java
  src/main/java/com/seeat/server/domain/manage/presentation/FeedbackController.java
  src/main/java/com/seeat/server/domain/manage/presentation/swagger/FeedbackControllerSpec.java
  src/main/java/com/seeat/server/domain/review/application/ReviewService.java
  src/main/java/com/seeat/server/domain/review/application/ReviewUseCase.java
  src/main/java/com/seeat/server/domain/review/domain/entity/Bookmark.java
  src/main/java/com/seeat/server/domain/review/domain/entity/HashTag.java
  src/main/java/com/seeat/server/domain/review/domain/entity/Review.java
  src/main/java/com/seeat/server/domain/review/domain/entity/ReviewHashTag.java
  src/main/java/com/seeat/server/domain/review/domain/entity/ReviewImage.java
  src/main/java/com/seeat/server/domain/review/domain/entity/ReviewLike.java
  src/main/java/com/seeat/server/domain/review/domain/repository/BookmarkRepository.java
  src/main/java/com/seeat/server/domain/review/domain/repository/HashTagRepository.java
  src/main/java/com/seeat/server/domain/review/domain/repository/ReviewHashTagRepository.java
  src/main/java/com/seeat/server/domain/review/domain/repository/ReviewImageRepository.java
  src/main/java/com/seeat/server/domain/review/domain/repository/ReviewLikeRepository.java
  src/main/java/com/seeat/server/domain/review/domain/repository/ReviewRepository.java
  src/main/java/com/seeat/server/domain/review/presentation/ReviewController.java
  src/main/java/com/seeat/server/domain/review/presentation/swagger/ReviewControllerSpec.java
  src/main/java/com/seeat/server/domain/theater/application/TheaterService.java
  src/main/java/com/seeat/server/domain/theater/application/TheaterUseCase.java
  src/main/java/com/seeat/server/domain/theater/domain/entity/Auditorium.java
  src/main/java/com/seeat/server/domain/theater/domain/entity/AuditoriumType.java
  src/main/java/com/seeat/server/domain/theater/domain/entity/Movie.java
  src/main/java/com/seeat/server/domain/theater/domain/entity/MovieGenre.java
  src/main/java/com/seeat/server/domain/theater/domain/entity/Seat.java
  src/main/java/com/seeat/server/domain/theater/domain/entity/SeatRatingSummary.java
  src/main/java/com/seeat/server/domain/theater/domain/entity/Theater.java
  src/main/java/com/seeat/server/domain/theater/domain/repository/AuditoriumRepository.java
  src/main/java/com/seeat/server/domain/theater/domain/repository/MovieRepository.java
  src/main/java/com/seeat/server/domain/theater/domain/repository/SeatRatingSummaryRepository.java
  src/main/java/com/seeat/server/domain/theater/domain/repository/SeatRepository.java
  src/main/java/com/seeat/server/domain/theater/domain/repository/TheaterRepository.java
  src/main/java/com/seeat/server/domain/theater/presentation/TheaterController.java
  src/main/java/com/seeat/server/domain/theater/presentation/swagger/TheaterControllerSpec.java
  src/main/java/com/seeat/server/domain/user/application/UserService.java
  src/main/java/com/seeat/server/domain/user/application/UserUseCase.java
  src/main/java/com/seeat/server/domain/user/domain/entity/User.java
  src/main/java/com/seeat/server/domain/user/domain/entity/UserGrade.java
  src/main/java/com/seeat/server/domain/user/domain/entity/UserRole.java
  src/main/java/com/seeat/server/domain/user/domain/entity/UserSocial.java
  src/main/java/com/seeat/server/domain/user/domain/entity/UserTheater.java
  src/main/java/com/seeat/server/domain/user/domain/repository/UserRepository.java
  src/main/java/com/seeat/server/domain/user/domain/repository/UserTheaterRepository.java
  src/main/java/com/seeat/server/domain/user/presentation/UserController.java
  src/main/java/com/seeat/server/domain/user/presentation/swagger/UserControllerSpec.java
  src/main/java/com/seeat/server/global/config/MongoConfig.java
  src/main/java/com/seeat/server/global/config/RedisConfig.java
  src/main/java/com/seeat/server/global/config/SwaggerConfig.java
  src/main/java/com/seeat/server/global/config/WebConfig.java
  src/main/java/com/seeat/server/global/exception/GlobalExceptionHandler.java
  src/main/java/com/seeat/server/global/response/.gitkeep
  src/main/java/com/seeat/server/security/config/SecurityConfig.java
  src/main/java/com/seeat/server/security/jwt/.gitkeep
  src/main/java/com/seeat/server/security/oauth2/.gitkeep
Labels: ⚙ Setting

#4 ✨feat: CICD파이프라인 설정 및 SSL 설정
  .github/workflows/ci-test.yml
  .github/workflows/dev-ci-cd.yml
  Dockerfile
  build.gradle
  setting/docker-compose.yml
  setting/nginx/nginx.conf
  src/main/resources/static/index.html
  src/main/resources/static/style.css
Labels: 🌏 Deploy

#23 ✨feat: 공통 응답/에러 반영 및 개발용 토큰 발급 기능 구현하기
  src/main/java/com/seeat/server/domain/user/application/UserService.java
  src/main/java/com/seeat/server/domain/user/application/UserUseCase.java
  src/main/java/com/seeat/server/domain/user/application/dto/UserSignUpRequest.java
  src/main/java/com/seeat/server/domain/user/domain/entity/User.java
  src/main/java/com/seeat/server/domain/user/domain/entity/UserTheater.java
  src/main/java/com/seeat/server/domain/user/presentation/UserController.java
  src/main/java/com/seeat/server/domain/user/presentation/swagger/UserControllerSpec.java
  src/main/java/com/seeat/server/global/response/ErrorCode.java
  src/main/java/com/seeat/server/global/util/JwtConstants.java
  src/main/java/com/seeat/server/security/config/SecurityConfig.java
  src/main/java/com/seeat/server/security/handler/CustomOAuth2SuccessHandler.java
  src/main/java/com/seeat/server/security/jwt/JwtFilter.java
  src/main/java/com/seeat/server/security/jwt/JwtProvider.java
  src/main/java/com/seeat/server/security/jwt/service/TokenService.java
  src/main/java/com/seeat/server/security/oauth2/application/CustomOAuth2UserService.java
  src/test/java/com/seeat/server/UserControllerTest.java
Labels: ✨ Feature

#30 ♻️ refactor : 도커 컴포즈 volume 수정 및 개발용 레디스 추가
  .github/workflows/dev-ci-cd.yml
  setting/docker-compose.yml
  setting/mysql/cond.f/my.cnf
Labels: 🔨 Refactor

#31 ✨ feat : 영화관 기능 구현
  src/main/java/com/seeat/server/domain/review/application/dto/request/ReviewRequest.java
  src/main/java/com/seeat/server/domain/review/application/service/ReviewService.java
  src/main/java/com/seeat/server/domain/review/application/usecase/ReviewUseCase.java
  src/main/java/com/seeat/server/domain/review/domain/repository/ReviewRepository.java
  src/main/java/com/seeat/server/domain/review/presentation/ReviewController.java
  src/main/java/com/seeat/server/domain/review/presentation/swagger/ReviewControllerSpec.java
  src/main/java/com/seeat/server/domain/theater/application/TheaterService.java
  src/main/java/com/seeat/server/domain/theater/application/TheaterUseCase.java
  src/main/java/com/seeat/server/domain/theater/application/dto/response/AuditoriumDetailResponse.java
  src/main/java/com/seeat/server/domain/theater/application/dto/response/SeatListResponse.java
  src/main/java/com/seeat/server/domain/theater/application/dto/response/TheaterListResponse.java
  src/main/java/com/seeat/server/domain/theater/domain/entity/Auditorium.java
  src/main/java/com/seeat/server/domain/theater/domain/entity/AuditoriumType.java
  src/main/java/com/seeat/server/domain/theater/domain/entity/Seat.java
  src/main/java/com/seeat/server/domain/theater/domain/entity/Theater.java
  src/main/java/com/seeat/server/domain/theater/domain/repository/AuditoriumRepository.java
  src/main/java/com/seeat/server/domain/theater/domain/repository/SeatRepository.java
  src/main/java/com/seeat/server/domain/theater/domain/repository/TheaterRepository.java
  src/main/java/com/seeat/server/domain/theater/presentation/TheaterAuditoriumTypeConverter.java
  src/main/java/com/seeat/server/domain/theater/presentation/TheaterController.java
  src/main/java/com/seeat/server/domain/theater/presentation/swagger/TheaterControllerSpec.java
  src/main/java/com/seeat/server/domain/user/application/UserService.java
  src/main/java/com/seeat/server/domain/user/application/dto/UserSignUpRequest.java
  src/main/java/com/seeat/server/security/config/RequestMatcherHolder.java
  src/test/java/com/seeat/server/domain/seat/domain/AuditoriumFixtures.java
  src/test/java/com/seeat/server/domain/seat/domain/SeatFixtures.java
  src/test/java/com/seeat/server/domain/seat/domain/TheaterFixtures.java
  src/test/java/com/seeat/server/domain/user/presentation/UserControllerTest.java
Labels: ✨ Feature

#35 ✨ feat: 마이페이지 기능 구현하기
  src/main/java/com/seeat/server/domain/user/application/UserService.java
  src/main/java/com/seeat/server/domain/user/application/UserUseCase.java
  src/main/java/com/seeat/server/domain/user/application/dto/request/UserInfoUpdateRequest.java
  src/main/java/com/seeat/server/domain/user/application/dto/request/UserSignUpRequest.java
  src/main/java/com/seeat/server/domain/user/application/dto/response/UserGradeResponse.java
  src/main/java/com/seeat/server/domain/user/application/dto/response/UserInfoResponse.java
  src/main/java/com/seeat/server/domain/user/application/dto/response/UserInfoUpdateResponse.java
  src/main/java/com/seeat/server/domain/user/domain/entity/User.java
  src/main/java/com/seeat/server/domain/user/presentation/UserController.java
  src/main/java/com/seeat/server/domain/user/presentation/UserProfileController.java
  src/main/java/com/seeat/server/domain/user/presentation/swagger/UserControllerSpec.java
  src/main/java/com/seeat/server/domain/user/presentation/swagger/UserProfileControllerSpec.java
  src/test/java/com/seeat/server/domain/user/application/service/UserServiceTest.java
  src/test/java/com/seeat/server/domain/user/presentation/UserControllerTest.java
Labels: ✨ Feature

#42 ✨ feat : 마이페이지 상영관 연결 구현하기
  src/main/java/com/seeat/server/domain/review/application/service/BookmarkService.java
  src/main/java/com/seeat/server/domain/review/application/service/ReviewLikeService.java
  src/main/java/com/seeat/server/domain/review/application/service/ReviewService.java
  src/main/java/com/seeat/server/domain/theater/application/TheaterService.java
  src/main/java/com/seeat/server/domain/theater/application/dto/response/AuditoriumResponse.java
  src/main/java/com/seeat/server/domain/user/application/dto/request/UserInfoUpdateRequest.java
  src/main/java/com/seeat/server/domain/user/application/dto/response/UserInfoResponse.java
  src/main/java/com/seeat/server/domain/user/application/dto/response/UserInfoUpdateResponse.java
  src/main/java/com/seeat/server/domain/user/application/service/UserProfileService.java
  src/main/java/com/seeat/server/domain/user/application/service/UserService.java
  src/main/java/com/seeat/server/domain/user/application/usecase/UserProfileUseCase.java
  src/main/java/com/seeat/server/domain/user/application/usecase/UserUseCase.java
  src/main/java/com/seeat/server/domain/user/domain/entity/UserAuditorium.java
  src/main/java/com/seeat/server/domain/user/domain/repository/UserAuditoriumRepository.java
  src/main/java/com/seeat/server/domain/user/domain/repository/UserTheaterRepository.java
  src/main/java/com/seeat/server/domain/user/presentation/UserController.java
  src/main/java/com/seeat/server/domain/user/presentation/UserProfileController.java
  src/main/java/com/seeat/server/security/config/RequestMatcherHolder.java
  src/main/java/com/seeat/server/security/oauth2/application/CustomOAuth2UserService.java
  src/test/java/com/seeat/server/domain/seat/domain/AuditoriumFixtures.java
  src/test/java/com/seeat/server/domain/user/application/service/UserProfileServiceTest.java
  src/test/java/com/seeat/server/domain/user/presentation/UserControllerTest.java
Labels: ✨ Feature

#45 ♻️ refactor : 나의 북마크 및 후기 마이페이지로 이동
  src/main/java/com/seeat/server/domain/review/application/dto/request/ReviewRequest.java
  src/main/java/com/seeat/server/domain/review/application/service/ReviewService.java
  src/main/java/com/seeat/server/domain/review/application/usecase/ReviewUseCase.java
  src/main/java/com/seeat/server/domain/review/domain/repository/ReviewRepository.java
  src/main/java/com/seeat/server/domain/review/presentation/BookmarkController.java
  src/main/java/com/seeat/server/domain/review/presentation/ReviewController.java
  src/main/java/com/seeat/server/domain/review/presentation/swagger/BookmarkControllerSpec.java
  src/main/java/com/seeat/server/domain/review/presentation/swagger/ReviewControllerSpec.java
  src/main/java/com/seeat/server/domain/theater/application/service/TheaterService.java
  src/main/java/com/seeat/server/domain/theater/application/usecase/TheaterUseCase.java
  src/main/java/com/seeat/server/domain/theater/domain/repository/SeatRepository.java
  src/main/java/com/seeat/server/domain/user/presentation/UserProfileController.java
  src/main/java/com/seeat/server/domain/user/presentation/swagger/UserProfileControllerSpec.java
  src/main/java/com/seeat/server/security/config/RequestMatcherHolder.java
  src/test/java/com/seeat/server/domain/review/application/service/ReviewServiceIntTest.java
  src/test/java/com/seeat/server/domain/theater/application/service/SeatRatingServiceIntTest.java
Labels: 🔨 Refactor

#65 feat: 피드백 테스트 코드 수정
  src/main/java/com/seeat/server/global/response/ErrorCode.java
  src/test/java/com/seeat/server/domain/feedback/application/service/FeedbackServiceIntTest.java
Labels: ✅ Test
