Repository Leets-Official/SEEAT-BE, pull requests merged in 2025-08, with the labels that each got.

#60 ✨ feat : 상영관에 자주 쓰이는 해시태그 목록 조회
  src/main/java/com/seeat/server/domain/review/application/dto/response/AuditoriumHashTagResponse.java
  src/main/java/com/seeat/server/domain/review/application/service/ReviewHashTagService.java
  src/main/java/com/seeat/server/domain/review/application/service/ReviewService.java
  src/main/java/com/seeat/server/domain/review/application/usecase/ReviewHashTagUseCase.java
  src/main/java/com/seeat/server/domain/review/application/usecase/ReviewUseCase.java
  src/main/java/com/seeat/server/domain/review/domain/repository/ReviewHashTagRepository.java
  src/main/java/com/seeat/server/domain/review/domain/repository/dto/ReviewHashTagWithCount.java
  src/main/java/com/seeat/server/domain/review/presentation/HashTagController.java
  src/main/java/com/seeat/server/domain/review/presentation/swagger/HashTagControllerSpec.java
  src/test/java/com/seeat/server/domain/review/application/service/ReviewHashTagServiceIntTest.java
  src/test/java/com/seeat/server/domain/review/domain/ReviewFixtures.java
Labels: ✨ Feature

#69 ♻️ refactor : 상영관 배치도에 따른 도메인 수정
  src/main/java/com/seeat/server/domain/theater/application/dto/response/AuditoriumDetailResponse.java
  src/main/java/com/seeat/server/domain/theater/application/dto/response/TheaterListResponse.java
  src/main/java/com/seeat/server/domain/theater/domain/entity/Auditorium.java
Labels: 🔨 Refactor

#82 🔥fix : 개발용 토큰 마이페이지 조회시 에러 문제 해결
  src/main/java/com/seeat/server/security/jwt/JwtProvider.java
  src/main/resources/data.sql
Labels: 🐞 BugFix

#84 ♻️ refactor : OCR 전달 시 좌석 정보 전달
  src/main/java/com/seeat/server/domain/review/application/dto/response/OcrResponse.java
  src/main/java/com/seeat/server/domain/review/application/service/TicketOcrService.java
  src/main/java/com/seeat/server/domain/theater/application/service/TheaterService.java
  src/main/java/com/seeat/server/domain/theater/application/usecase/TheaterUseCase.java
  src/main/java/com/seeat/server/domain/theater/domain/repository/AuditoriumRepository.java
  src/main/java/com/seeat/server/domain/theater/domain/repository/SeatRepository.java
  src/main/java/com/seeat/server/domain/theater/domain/repository/TheaterRepository.java
  src/main/java/com/seeat/server/global/response/ErrorCode.java
Labels: 🔨 Refactor

#79 ♻️ refactor : 리뷰 요구사항 수정
  src/main/java/com/seeat/server/domain/best/application/dto/response/BestReviewListResponse.java
  src/main/java/com/seeat/server/domain/best/application/util/SnapShotConverter.java
  src/main/java/com/seeat/server/domain/best/domain/entity/BestReviewSnapshot.java
  src/main/java/com/seeat/server/domain/review/application/dto/request/ReviewRequest.java
  src/main/java/com/seeat/server/domain/review/application/dto/request/ReviewSortType.java
  src/main/java/com/seeat/server/domain/review/application/dto/request/ReviewUpdateRequest.java
  src/main/java/com/seeat/server/domain/review/application/dto/response/AuditoriumHashTagResponse.java
  src/main/java/com/seeat/server/domain/review/application/dto/response/ReviewDetailResponse.java
  src/main/java/com/seeat/server/domain/review/application/dto/response/ReviewListResponse.java
  src/main/java/com/seeat/server/domain/review/application/dto/response/ReviewSeatInfoResponse.java
  src/main/java/com/seeat/server/domain/review/application/dto/response/ReviewSeatListResponse.java
  src/main/java/com/seeat/server/domain/review/application/service/ReviewHashTagService.java
  src/main/java/com/seeat/server/domain/review/application/service/ReviewService.java
  src/main/java/com/seeat/server/domain/review/application/usecase/ReviewUseCase.java
  src/main/java/com/seeat/server/domain/review/domain/entity/Review.java
  src/main/java/com/seeat/server/domain/review/domain/repository/ReviewRepository.java
  src/main/java/com/seeat/server/domain/review/domain/repository/dto/SeatReviewStats.java
  src/main/java/com/seeat/server/domain/review/presentation/ReviewController.java
  src/main/java/com/seeat/server/domain/review/presentation/ReviewSortTypeConverter.java
  src/main/java/com/seeat/server/domain/review/presentation/swagger/ReviewControllerSpec.java
  src/main/java/com/seeat/server/global/response/ErrorCode.java
  src/main/java/com/seeat/server/global/util/DateFormatUtil.java
  src/test/java/com/seeat/server/domain/best/application/service/BestContentServiceIntTest.java
  src/test/java/com/seeat/server/domain/bookmark/application/service/BookmarkServiceIntTest.java
  src/test/java/com/seeat/server/domain/review/application/service/ReviewServiceIntTest.java
  src/test/java/com/seeat/server/domain/review/domain/ReviewFixtures.java
Labels: ✨ Feature, 🔨 Refactor

#93 🔥fix : 기존 사용자 로그인 시 토큰 발급 실패 문제 해결
  src/main/java/com/seeat/server/security/handler/CustomOAuth2SuccessHandler.java
  src/main/java/com/seeat/server/security/jwt/JwtProvider.java
  src/main/java/com/seeat/server/security/jwt/service/TokenService.java
  src/test/java/com/seeat/server/security/handler/CustomOAuth2SuccessHandlerTest.java
Labels: 🐞 BugFix

#87 ✨feat: 마이페이지 조회 DTO 경험치 추가 구현
  src/main/java/com/seeat/server/domain/review/application/dto/response/ReviewLikeCountResponse.java
  src/main/java/com/seeat/server/domain/review/domain/repository/ReviewRepository.java
  src/main/java/com/seeat/server/domain/user/application/dto/response/UserInfoResponse.java
  src/main/java/com/seeat/server/domain/user/application/service/UserProfileService.java
  src/main/java/com/seeat/server/domain/user/domain/entity/User.java
  src/main/java/com/seeat/server/global/response/ErrorCode.java
  src/test/java/com/seeat/server/domain/user/application/service/UserProfileServiceTest.java
  src/test/java/com/seeat/server/domain/user/domain/UserFixtures.java
Labels: ✨ Feature, 🔨 Refactor

#94 🔥 fix : 좌석명 표기 오류 및 작성시간, Swagger 양식 수정
  src/main/java/com/seeat/server/domain/review/application/dto/response/ReviewDetailResponse.java
  src/main/java/com/seeat/server/domain/review/application/dto/response/ReviewSeatInfoResponse.java
  src/main/java/com/seeat/server/domain/review/presentation/ReviewController.java
  src/main/java/com/seeat/server/domain/review/presentation/swagger/ReviewControllerSpec.java
Labels: 🐞 BugFix, 🔨 Refactor

#91 ♻️refactor: 장르 max개수 수정 및 유저 닉네임 중복 확인 구현
  src/main/java/com/seeat/server/domain/user/application/dto/request/UserSignUpRequest.java
  src/main/java/com/seeat/server/domain/user/application/dto/response/UserNicknameResponse.java
  src/main/java/com/seeat/server/domain/user/application/service/UserService.java
  src/main/java/com/seeat/server/domain/user/application/usecase/UserUseCase.java
  src/main/java/com/seeat/server/domain/user/domain/repository/UserRepository.java
  src/main/java/com/seeat/server/domain/user/presentation/UserController.java
  src/main/java/com/seeat/server/domain/user/presentation/swagger/UserControllerSpec.java
  src/main/java/com/seeat/server/global/response/ErrorCode.java
  src/main/java/com/seeat/server/security/config/RequestMatcherHolder.java
Labels: ✨ Feature, 🔨 Refactor

#103 ♻️refactor: 회원가입시 토큰 발급 추가 + 개발용 토큰 발급 시 문제 해결
  src/main/java/com/seeat/server/domain/review/domain/repository/ReviewRepository.java
  src/main/java/com/seeat/server/domain/user/application/service/UserService.java
  src/main/java/com/seeat/server/domain/user/application/usecase/UserUseCase.java
  src/main/java/com/seeat/server/domain/user/domain/repository/UserAuditoriumRepository.java
  src/main/java/com/seeat/server/domain/user/presentation/UserController.java
  src/main/java/com/seeat/server/domain/user/presentation/swagger/UserControllerSpec.java
  src/main/java/com/seeat/server/security/jwt/JwtProvider.java
  src/test/java/com/seeat/server/domain/user/application/service/UserProfileServiceTest.java
Labels: ✨ Feature, 🔨 Refactor

#110 🔥 hotfix : 프론트 헤더 접근 권한 문제 수정
  src/main/java/com/seeat/server/domain/auth/application/dto/response/TokenResponse.java
  src/main/java/com/seeat/server/domain/auth/presentation/AuthController.java
  src/main/java/com/seeat/server/domain/auth/presentation/swagger/AuthControllerSpec.java
  src/main/java/com/seeat/server/global/service/RedisService.java
  src/main/java/com/seeat/server/security/config/CorsConfig.java
  src/main/java/com/seeat/server/security/config/RequestMatcherHolder.java
  src/main/java/com/seeat/server/security/jwt/service/TokenService.java
Labels: 🐞 BugFix
